# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [63]:
import numpy as np
import random
import scipy.stats as sps
import cv2

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [64]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
print("ранг a =",a.ndim, "\nранг b =", b.ndim, '\n')
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape, '\n')

print("Матрица a =",a, '\n')

print("Матрица b =",b)

ранг a = 2 
ранг b = 2 

размер матрицы a = (100, 100) 
размер матрицы b = (100, 100) 

Матрица a = [[0.38987546 0.89442913 0.72524552 ... 0.65354806 0.63425144 0.56334277]
 [0.77175537 0.92853006 0.26075475 ... 0.65641221 0.36971519 0.74826801]
 [0.06300928 0.92929501 0.50084131 ... 0.6726973  0.92562376 0.94078624]
 ...
 [0.97331719 0.50980224 0.61198512 ... 0.61826111 0.67100957 0.32577078]
 [0.3285206  0.94352601 0.85237138 ... 0.57737778 0.27998275 0.63139784]
 [0.63451557 0.76181882 0.69168209 ... 0.16156867 0.38776655 0.60883951]] 

Матрица b = [[0.60391535 0.03931646 0.62797243 ... 0.86603274 0.00569828 0.4255496 ]
 [0.87066721 0.56971733 0.84658319 ... 0.10119231 0.88563827 0.53071304]
 [0.85560257 0.77157142 0.99734448 ... 0.04851943 0.58796486 0.56368264]
 ...
 [0.04421953 0.10869431 0.46557037 ... 0.83209954 0.64756373 0.43838462]
 [0.51548019 0.10515166 0.67279906 ... 0.0316039  0.77211204 0.16769383]
 [0.02198973 0.41506487 0.77825602 ... 0.54670764 0.11240627 0.70331735]

Без использования numpy

In [65]:
def mult(a, b):
  # Матрица result, что будет содержать результат умножения матриц a и b.
  # Размерность этой матрицы равна числу строк матрицы a на число столбцов матрицы b.
  result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]
  for _a in range(len(a)):
    for _b in range(len(b[0])):
      for _ab in range(len(b)):
        # Внутри вложенных циклов происходит умножение соответствующих элементов матриц
        # a и b, после чего результат прибавляется к соответствующему элементу матрицы result
        result[_a][_b] += a[_a][_ab] * b[_ab][_b]
  return result

C использованием numpy

In [66]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [67]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 470 ms, sys: 0 ns, total: 470 ms
Wall time: 473 ms


In [68]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.14 ms, sys: 1.06 ms, total: 2.2 ms
Wall time: 1.68 ms


In [69]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()
# Результатом должен быть 0 (или очень малое число, из-за "плавающей запятой")

1.5150547483244736e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [70]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.87851346 0.26137561 0.49090933] [0.37487291 0.58333226 0.67545043]


In [71]:
def scalar_product(a, b):
    s = sum(ai * bi for ai, bi in zip(a, b))
    # zip(a, b): Функция zip используется для создания итератора,
    # который комбинирует элементы из векторов a и b попарно.
    # Таким образом, на каждом шаге получаем пару элементов (ai, bi).
    return s

In [72]:
def np_scalar_product(a, b):
    s = np.dot(a, b)
    return s

In [73]:
%time product_1 = scalar_product(a,b)
print('')
%time product_2 = np_scalar_product(a,b)
print('')

# Проверим корректность:
print('Если ниже 0.0, то всё отлично')
np.abs(product_1 - product_2).sum()
# Результатом должен быть 0.0

CPU times: user 25 µs, sys: 0 ns, total: 25 µs
Wall time: 29.1 µs

CPU times: user 30 µs, sys: 0 ns, total: 30 µs
Wall time: 33.6 µs

Если ниже 0.0, то всё отлично


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:**
Numpy оказываются эффективнее, т.к. он предоставляет оптимальные методы работы с массивами и матрицами, что основаны на оптимизированных вычислительных операциях языков C и Fortran.

Что касается скорости вычислений - в NumPy она обычно выше, чем в чистом Python, особенно при работе с большими массивами данных. Операции в NumPy выполняются на более низком уровне языков программирования (опять же, C и Fortran). Они оптимизированы для работы с массивами, что приводит к значительному ускорению по сравнению с общими операциями в Python.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [74]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diagonal_el = np.diag(a)
  # Выбираем четные элементы
  even_diagonal_el = diagonal_el[diagonal_el % 2 == 0]
  # Если есть четные элементы, возвращаем их сумму, иначе возвращаем 0
  if even_diagonal_el.size > 0:
    return even_diagonal_el.sum()
  else:
    return 0

In [75]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[3, 2, 5, 1, 5],
       [8, 3, 8, 4, 3],
       [9, 2, 5, 1, 6],
       [6, 3, 4, 8, 5],
       [1, 3, 1, 2, 3]])

In [76]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 78 µs, sys: 13 µs, total: 91 µs
Wall time: 95.4 µs


8

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [77]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
  A = np.array(A)
  # Используем cumsum для вычисления накопленной суммы
  cumsum_A = np.cumsum(A, axis=1)
  # Вычисляем s_k = (x1 + ... + xk) / k для каждого k
  k_values = np.arange(1, A.shape[1] + 1)
  result = cumsum_A / k_values.reshape(1, -1)
  return result

In [78]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.79443695 0.20295319 0.46821582 0.2324671  0.35930963 0.70623486
 0.6280514  0.35559654 0.88416553 0.11565099 0.25924502 0.16760439
 0.48157878 0.46661037 0.45773982 0.69471463 0.78907395 0.16912933
 0.93373616 0.80649441 0.39229758 0.45977343 0.54995119 0.43838414
 0.69305925 0.15494856 0.17971626 0.64972149 0.04122233 0.10128172
 0.52167192 0.74334181 0.22855691 0.48019784 0.58348226 0.74220891
 0.1073866  0.83855434 0.6588725  0.96025117 0.96425223 0.48869474
 0.57475713 0.95417449 0.998237   0.4877182  0.95498724 0.78962395
 0.06438927 0.76644601 0.47008044 0.53131589 0.67987706 0.43648263
 0.12531868 0.39507298 0.50153198 0.58453893 0.81162955 0.66758174
 0.63552068 0.00747078 0.07038034 0.91104617 0.92979297 0.35253519
 0.51616827 0.02659784 0.6435935  0.1058611  0.96093674 0.34403389
 0.31542684 0.19764553 0.04309259 0.76562313 0.47492066 0.7652095
 0.47214387 0.90282257 0.75198128 0.01261584 0.51651216 0.44203301
 0.34840396 0.26260243 0.40166823 0.36708923 0.67355375 0.79322

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [79]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
  # Используем функцию groupby из itertools для группировки повторяющихся элементов
  grouped_elements = [(key, len(list(group))) for key, group in groupby(a)]
  # Разделяем результат на два массива
  x, num = zip(*grouped_elements)
  return np.array(x), np.array(num)

In [80]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 40 µs, sys: 0 ns, total: 40 µs
Wall time: 43.9 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [81]:
# функция, решающая задачу с помощью NumPy
def np_transformation(X, a=1):
  # Создаем копию массива X для сохранения оригинала
  result = np.copy(X)
  # Заменяем элементы с нечетными индексами на a
  result[1::2] = a
  # Возводим элементы с четными индексами в куб
  result[::2] **= 3
  # Создаем новый массив, в котором элементы записаны в обратном порядке
  reversed_result = result[::-1]
  # Сливаем массивы X и reversed_result
  final_result = np.concatenate([X, reversed_result])
  return final_result

In [82]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 93 µs, sys: 0 ns, total: 93 µs
Wall time: 108 µs
